// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtSMUHXX5u9fZPQFA-cnXxM-nuL7zY4YQ',
    appId: '1:639407102952:web:6110c6e32402c9cdd0a25d',
    messagingSenderId: '639407102952',
    projectId: 'authtutorial-8e071',
    authDomain: 'authtutorial-8e071.firebaseapp.com',
    storageBucket: 'authtutorial-8e071.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7_5zq09ZGALLJs2PlXb1V_7E1yBRC8os',
    appId: '1:639407102952:android:a1ce5f7203e33305d0a25d',
    messagingSenderId: '639407102952',
    projectId: 'authtutorial-8e071',
    storageBucket: 'authtutorial-8e071.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_FUR_ID7gxdgnFJixv5qVP_8CcnfpZsA',
    appId: '1:639407102952:ios:8064b148d14728b1d0a25d',
    messagingSenderId: '639407102952',
    projectId: 'authtutorial-8e071',
    storageBucket: 'authtutorial-8e071.firebasestorage.app',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_FUR_ID7gxdgnFJixv5qVP_8CcnfpZsA',
    appId: '1:639407102952:ios:8064b148d14728b1d0a25d',
    messagingSenderId: '639407102952',
    projectId: 'authtutorial-8e071',
    storageBucket: 'authtutorial-8e071.firebasestorage.app',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtSMUHXX5u9fZPQFA-cnXxM-nuL7zY4YQ',
    appId: '1:639407102952:web:d28abacb49209e34d0a25d',
    messagingSenderId: '639407102952',
    projectId: 'authtutorial-8e071',
    authDomain: 'authtutorial-8e071.firebaseapp.com',
    storageBucket: 'authtutorial-8e071.firebasestorage.app',
  );
}
