// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqhmPkCfNs3dFUpkq9IELKsGUWGcW7H8M',
    appId: '1:651569794200:web:6a6ab78f16fb680acdd4ed',
    messagingSenderId: '651569794200',
    projectId: 'fir-crud-17ba4',
    authDomain: 'fir-crud-17ba4.firebaseapp.com',
    storageBucket: 'fir-crud-17ba4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD11X_m0jcRy-Kc3OVdw394rgc5ZPc6NiA',
    appId: '1:651569794200:android:f0ef054d9b1174c4cdd4ed',
    messagingSenderId: '651569794200',
    projectId: 'fir-crud-17ba4',
    storageBucket: 'fir-crud-17ba4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDqsJiY6eZeeMJARUkSn-SC2pNHpbfL8A',
    appId: '1:651569794200:ios:f251a3cc06884d52cdd4ed',
    messagingSenderId: '651569794200',
    projectId: 'fir-crud-17ba4',
    storageBucket: 'fir-crud-17ba4.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDqsJiY6eZeeMJARUkSn-SC2pNHpbfL8A',
    appId: '1:651569794200:ios:f251a3cc06884d52cdd4ed',
    messagingSenderId: '651569794200',
    projectId: 'fir-crud-17ba4',
    storageBucket: 'fir-crud-17ba4.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqhmPkCfNs3dFUpkq9IELKsGUWGcW7H8M',
    appId: '1:651569794200:web:53081f7226234d8fcdd4ed',
    messagingSenderId: '651569794200',
    projectId: 'fir-crud-17ba4',
    authDomain: 'fir-crud-17ba4.firebaseapp.com',
    storageBucket: 'fir-crud-17ba4.firebasestorage.app',
  );
}
